# Generated by Django 4.1.7 on 2023-02-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer_name", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
    ]
