# Generated by Django 4.1.7 on 2023-02-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("species", models.CharField(max_length=200)),
                ("sex", models.CharField(max_length=200)),
                ("status", models.CharField(max_length=200)),
                ("age", models.SmallIntegerField()),
                ("picture", models.URLField(null=True)),
                ("intake_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
